// All the Generic Data which will be used through out the app will go here

import randomstring from "randomstring";
import * as Icons from "react-feather";

function sectionsList() {
  return [
    {
      category: "yoga",
      primaryColor: "rose",
      secondaryColor: "rose",
      tertiaryColor: "yellow",
      sections: [
        { id: "headerYoga", type: null },
        { id: "heroYoga", type: "about-us", elements: 1 },
        { id: "headerInsuranceAgent", type: "about-us", elements: 1 },
        { id: "hero2Yoga", type: "hero", elements: 3 },
        { id: "hero3Yoga", type: "hero", elements: 3 },
        { id: "galleryYoga", type: "gallery", elements: 3 },
        { id: "featureYoga", type: "features", elements: 3 },
        { id: "testimonialYoga", type: "testimonials", elements: 6 },
        { id: "gallery2Yoga", type: "gallery", elements: 3 },
        { id: "testimonial2Yoga", type: "testimonials", elements: 3 },
        { id: "contactYoga", type: null },
      ],
    },
    {
      category: "insurance",
      primaryColor: "blue",
      secondaryColor: "blue",
      tertiaryColor: "indigos",
      sections: [
        { id: "heroInsurance", type: "about-us", elements: 1 },
        { id: "heroInsurance1", type: "hero", elements: 3 },
        { id: "heroInsurance2", type: "hero", elements: 3 },
        { id: "galleryInsurance", type: "gallery", elements: 3 },
        { id: "featureInsurance", type: "features", elements: 3 },
        { id: "featureInsurance1", type: "features", elements: 3 },
        { id: "socialCardInsurance", type: "gallery", elements: 6 },
        { id: "footerInsurance", type: null },
        { id: "contactInsurance", type: null },
      ],
    },
    {
      category: "insuranceAgent",
      primaryColor: "blue",
      secondaryColor: "blue",
      tertiaryColor: "indigos",
      sections: [
        { id: "HeaderInsuranceAgent", type: "about-us", elements: 1 },
        { id: "HeroInsuranceAgent", type: "hero", elements: 3 },
        { id: "heroInsurance2", type: "hero", elements: 3 },
        { id: "galleryInsurance", type: "gallery", elements: 3 },
        { id: "FeatureInsuranceAgent", type: "features", elements: 3 },
        { id: "TestimonialInsuranceAgent", type: "testimonials", elements: 3 },
        { id: "FeatureInsuranceAgent1", type: "features", elements: 3 },
        { id: "FeatureInsuranceAgent2", type: "features", elements: 3 },
        { id: "GalleryInsuranceAgent", type: "gallery", elements: 6 },
        { id: "GalleryInsuranceAgent", type: "gallery", elements: 6 },
        { id: "FooterInsuranceAgent", type: null },
        { id: "ContactInsuranceAgent", type: null },
        { id: "ContactInsuranceAgent2", type: null },
      ],
    },

    {
      category: "artist",
      primaryColor: "rose",
      secondaryColor: "rose",
      tertiaryColor: "yellow",
      sections: [
        { id: "heroYoga", type: "about-us", elements: 1 },
        { id: "hero2Yoga", type: "hero", elements: 3 },
        { id: "hero3Yoga", type: "hero", elements: 3 },
        { id: "galleryYoga", type: "gallery", elements: 3 },
        { id: "featureYoga", type: "features", elements: 3 },
        { id: "testimonialYoga", type: "testimonials", elements: 6 },
        { id: "gallery2Yoga", type: "gallery", elements: 3 },
        { id: "testimonial2Yoga", type: "testimonials", elements: 3 },
        { id: "contactInsurance", type: null },
      ],
    },
    {
      category: "other",
      primaryColor: "rose",
      secondaryColor: "rose",
      tertiaryColor: "yellow",
      sections: [
        { id: "headerYoga", type: null },
        { id: "heroYoga", type: "about-us", elements: 1 },
        { id: "hero2Yoga", type: "hero", elements: 3 },
        { id: "hero3Yoga", type: "hero", elements: 3 },
        { id: "galleryYoga", type: "gallery", elements: 3 },
        { id: "featureYoga", type: "features", elements: 3 },
        { id: "testimonialYoga", type: "testimonials", elements: 6 },
        { id: "gallery2Yoga", type: "gallery", elements: 3 },
        { id: "testimonial2Yoga", type: "testimonials", elements: 3 },
        { id: "contactYoga", type: null },
      ],
    },
  ];
}

function componentCategoryList() {
  return [
    {
      category: ["artist"],
      templates: [
        {
          name: "PortfolioLight",
          componentMapping: {
            hero: [
              "HeroPortfolioLight",
              "HeroPortfolioLight1",
              "HeroPortfolioLight2",
              "HeroPortfolioLight3",
            ],
            gallery: ["GalleryPortfolioLight"],
            testimonial: ["TestimonialPortfolioLight"],
            socialcard: ["SocialCardPortfolioLight"],
            contact: ["ContactPortfolioLight"],
            footer: ["FooterPortfolioLight"],
          },
        },
        {
          name: "PortfolioDark",
          componentMapping: {
            hero: [
              "HeroPortfolioDark",
              "HeroPortfolioDark1",
              "HeroPortfolioDark2",
              "HeroPortfolioDark3",
            ],
            gallery: ["GalleryPortfolioDark"],
            testimonial: ["TestimonialPortfolioDark"],
            socialcard: ["SocialCardPortfolioDark"],
            contact: ["ContactPortfolioDark"],
            footer: ["FooterPortfolioDark"],
          },
        },
      ],
      identifier: "artist",
    },
    {
      category: ["insurance"],
      templates: [
        {
          name: "Insurance",
          componentMapping: {
            hero: ["HeroInsurance", "HeroInsurance1", "HeroInsurance2"],
            feature: ["FeatureInsurance", "FeatureInsurance1"],
            gallery: ["GalleryInsurance"],
            socialcard: ["SocialCardInsurance"],
            contact: ["ContactInsurance"],
            footer: ["FooterInsurance"],
          },
        },
      ],
      identifier: "insurance",
    },
    {
      category: ["yoga"],
      templates: [
        {
          name: "yogaTemp3",
          componentMapping: {
            header: ["HeaderYoga"],
            hero: ["HeroYoga", "Hero2Yoga", "Hero3Yoga"],
            feature: ["FeatureYoga"],
            gallery: ["GalleryYoga", "Gallery2Yoga"],
            testimonial: ["TestimonialYoga", "Testimonial2Yoga"],
            contact: ["ContactYoga"],
          },
        },
      ],
      identifier: "yoga",
    },
    {
      category: ["insuranceAgent"],
      templates: [
        {
          name: "insuranceAgent",
          componentMapping: {
            header: ["HeaderInsuranceAgent"],
            hero: ["HeroInsuranceAgent"],
            feature: [
              "FeatureInsuranceAgent,FeatureInsuranceAgent1,FeatureInsuranceAgent2",
            ],
            gallery: ["GalleryInsuranceAgent"],
            testimonial: ["TestimonialInsuranceAgent"],
            contact: ["ContactInsuranceAgent", "ContactInsuranceAgent2"],
          },
        },
      ],
      identifier: "insuranceAgent",
    },
    {
      category: ["other"],
      templates: [
        {
          name: "template1",
          componentMapping: {
            header: ["HeaderTemp1"],
            hero: ["HeroTemp1", "Hero2Temp1"],
            feature: ["FeatureTemp1"],
            client: ["ClientTemp1"],
            gallery: ["GalleryTemp1"],
            testimonial: ["Testimonial2Temp1", "TestimonialTemp1"],
            contact: ["ContactTemp1"],
            footer: ["FooterTemp1"],
          },
        },
        {
          name: "template2",
          componentMapping: {
            header: ["HeaderTemp2"],
            hero: ["HeroTemp2", "Hero2Temp2", "Hero3Temp2"],
            feature: ["FeatureTemp2"],
            client: ["ClientTemp2"],
            gallery: ["GalleryTemp2", "Gallery2Temp2"],
            testimonial: ["TestimonialTemp2"],
            contact: ["ContactTemp2"],
            footer: ["FooterTemp2"],
          },
        },

        {
          name: "template3",
          componentMapping: {
            header: ["HeaderTemp3"],
            hero: ["HeroTemp3", "Hero1Temp3", "Hero2Temp3", "Hero3Temp3"],
            feature: ["FeatureTemp3"],
            client: ["ClientsTemp3"],
            gallery: ["GalleryTemp3"],
            testimonial: ["TestimonialTemp3"],
            contact: ["ContactTemp3"],
            footer: ["FooterTemp3"],
          },
        },
        {
          name: "template4",
          componentMapping: {
            header: ["HeaderTemp4"],
            hero: ["HeroTemp4"],
            feature: ["FeatureTemp4"],
            client: ["ClientsTemp4"],
            gallery: ["GalleryTemp4", "Gallery2Temp4"],
            testimonial: ["TestimonialTemp4", "Testimonial2Temp4"],
            contact: ["ContactTemp4"],
            footer: ["FooterTemp4"],
          },
        },

        {
          name: "template5",
          componentMapping: {
            header: ["HeaderTemp5"],
            hero: ["HeroTemp5", "Hero1Temp5", "Hero2Temp5", "Hero3Temp5"],
            feature: ["FeatureTemp5"],
            client: ["ClientsTemp5"],
            gallery: ["GalleryTemp5", "Gallery1Temp5"],
            testimonial: ["TestimonialTemp5"],
            contact: ["ContactTemp5"],
            footer: ["FooterTemp5"],
          },
        },
        {
          name: "template6",
          componentMapping: {
            header: ["HeaderTemp6"],
            hero: ["HeroTemp6", "Hero1Temp6", "Hero2Temp6", "Hero3Temp6"],
            client: ["ClientsTemp6"],
            gallery: ["GalleryTemp6"],
            testimonial: ["TestimonialTemp6"],
            contact: ["ContactTemp6"],
            footer: ["FooterTemp6"],
          },
        },

        {
          name: "template7",
          componentMapping: {
            header: ["HeaderTemp7"],
            hero: ["HeroTemp7", "Hero1Temp7", "Hero2Temp7", "Hero3Temp7"],
            feature: ["FeatureTemp7"],
            client: ["ClientsTemp7"],
            gallery: ["GalleryTemp7"],
            testimonial: ["TestimonialTemp7"],
            contact: ["ContactTemp7"],
            footer: ["FooterTemp7"],
          },
        },
        {
          name: "template8",
          componentMapping: {
            header: ["HeaderTemp8"],
            hero: ["HeroTemp8", "Hero1Temp8", "Hero2Temp8"],
            feature: ["FeatureTemp8"],
            gallery: ["GalleryTemp8"],
            testimonial: ["TestimonialTemp8"],
            contact: ["ContactTemp8"],
            footer: ["FooterTemp8"],
          },
        },
      ],

      identifier: "other",
    },
  ];
}

function countriesList() {
  return [
    {
      name: "Afghanistan",
      value: "+93",
      label: "AF",
    },
    {
      name: "Aland Islands",
      value: "+358",
      label: "AX",
    },
    {
      name: "Albania",
      value: "+355",
      label: "AL",
    },
    {
      name: "Algeria",
      value: "+213",
      label: "DZ",
    },
    {
      name: "AmericanSamoa",
      value: "+1684",
      label: "AS",
    },
    {
      name: "Andorra",
      value: "+376",
      label: "AD",
    },
    {
      name: "Angola",
      value: "+244",
      label: "AO",
    },
    {
      name: "Anguilla",
      value: "+1264",
      label: "AI",
    },
    {
      name: "Antarctica",
      value: "+672",
      label: "AQ",
    },
    {
      name: "Antigua and Barbuda",
      value: "+1268",
      label: "AG",
    },
    {
      name: "Argentina",
      value: "+54",
      label: "AR",
    },
    {
      name: "Armenia",
      value: "+374",
      label: "AM",
    },
    {
      name: "Aruba",
      value: "+297",
      label: "AW",
    },
    {
      name: "Australia",
      value: "+61",
      label: "AU",
    },
    {
      name: "Austria",
      value: "+43",
      label: "AT",
    },
    {
      name: "Azerbaijan",
      value: "+994",
      label: "AZ",
    },
    {
      name: "Bahamas",
      value: "+1242",
      label: "BS",
    },
    {
      name: "Bahrain",
      value: "+973",
      label: "BH",
    },
    {
      name: "Bangladesh",
      value: "+880",
      label: "BD",
    },
    {
      name: "Barbados",
      value: "+1246",
      label: "BB",
    },
    {
      name: "Belarus",
      value: "+375",
      label: "BY",
    },
    {
      name: "Belgium",
      value: "+32",
      label: "BE",
    },
    {
      name: "Belize",
      value: "+501",
      label: "BZ",
    },
    {
      name: "Benin",
      value: "+229",
      label: "BJ",
    },
    {
      name: "Bermuda",
      value: "+1441",
      label: "BM",
    },
    {
      name: "Bhutan",
      value: "+975",
      label: "BT",
    },
    {
      name: "Bolivia, Plurinational State of",
      value: "+591",
      label: "BO",
    },
    {
      name: "Bosnia and Herzegovina",
      value: "+387",
      label: "BA",
    },
    {
      name: "Botswana",
      value: "+267",
      label: "BW",
    },
    {
      name: "Brazil",
      value: "+55",
      label: "BR",
    },
    {
      name: "British Indian Ocean Territory",
      value: "+246",
      label: "IO",
    },
    {
      name: "Brunei Darussalam",
      value: "+673",
      label: "BN",
    },
    {
      name: "Bulgaria",
      value: "+359",
      label: "BG",
    },
    {
      name: "Burkina Faso",
      value: "+226",
      label: "BF",
    },
    {
      name: "Burundi",
      value: "+257",
      label: "BI",
    },
    {
      name: "Cambodia",
      value: "+855",
      label: "KH",
    },
    {
      name: "Cameroon",
      value: "+237",
      label: "CM",
    },
    {
      name: "Canada",
      value: "+1",
      label: "CA",
    },
    {
      name: "Cape Verde",
      value: "+238",
      label: "CV",
    },
    {
      name: "Cayman Islands",
      value: "+ 345",
      label: "KY",
    },
    {
      name: "Central African Republic",
      value: "+236",
      label: "CF",
    },
    {
      name: "Chad",
      value: "+235",
      label: "TD",
    },
    {
      name: "Chile",
      value: "+56",
      label: "CL",
    },
    {
      name: "China",
      value: "+86",
      label: "CN",
    },
    {
      name: "Christmas Island",
      value: "+61",
      label: "CX",
    },
    {
      name: "Cocos (Keeling) Islands",
      value: "+61",
      label: "CC",
    },
    {
      name: "Colombia",
      value: "+57",
      label: "CO",
    },
    {
      name: "Comoros",
      value: "+269",
      label: "KM",
    },
    {
      name: "Congo",
      value: "+242",
      label: "CG",
    },
    {
      name: "Congo, The Democratic Republic of the Congo",
      value: "+243",
      label: "CD",
    },
    {
      name: "Cook Islands",
      value: "+682",
      label: "CK",
    },
    {
      name: "Costa Rica",
      value: "+506",
      label: "CR",
    },
    {
      name: "Cote d'Ivoire",
      value: "+225",
      label: "CI",
    },
    {
      name: "Croatia",
      value: "+385",
      label: "HR",
    },
    {
      name: "Cuba",
      value: "+53",
      label: "CU",
    },
    {
      name: "Cyprus",
      value: "+357",
      label: "CY",
    },
    {
      name: "Czech Republic",
      value: "+420",
      label: "CZ",
    },
    {
      name: "Denmark",
      value: "+45",
      label: "DK",
    },
    {
      name: "Djibouti",
      value: "+253",
      label: "DJ",
    },
    {
      name: "Dominica",
      value: "+1767",
      label: "DM",
    },
    {
      name: "Dominican Republic",
      value: "+1849",
      label: "DO",
    },
    {
      name: "Ecuador",
      value: "+593",
      label: "EC",
    },
    {
      name: "Egypt",
      value: "+20",
      label: "EG",
    },
    {
      name: "El Salvador",
      value: "+503",
      label: "SV",
    },
    {
      name: "Equatorial Guinea",
      value: "+240",
      label: "GQ",
    },
    {
      name: "Eritrea",
      value: "+291",
      label: "ER",
    },
    {
      name: "Estonia",
      value: "+372",
      label: "EE",
    },
    {
      name: "Ethiopia",
      value: "+251",
      label: "ET",
    },
    {
      name: "Falkland Islands (Malvinas)",
      value: "+500",
      label: "FK",
    },
    {
      name: "Faroe Islands",
      value: "+298",
      label: "FO",
    },
    {
      name: "Fiji",
      value: "+679",
      label: "FJ",
    },
    {
      name: "Finland",
      value: "+358",
      label: "FI",
    },
    {
      name: "France",
      value: "+33",
      label: "FR",
    },
    {
      name: "French Guiana",
      value: "+594",
      label: "GF",
    },
    {
      name: "French Polynesia",
      value: "+689",
      label: "PF",
    },
    {
      name: "Gabon",
      value: "+241",
      label: "GA",
    },
    {
      name: "Gambia",
      value: "+220",
      label: "GM",
    },
    {
      name: "Georgia",
      value: "+995",
      label: "GE",
    },
    {
      name: "Germany",
      value: "+49",
      label: "DE",
    },
    {
      name: "Ghana",
      value: "+233",
      label: "GH",
    },
    {
      name: "Gibraltar",
      value: "+350",
      label: "GI",
    },
    {
      name: "Greece",
      value: "+30",
      label: "GR",
    },
    {
      name: "Greenland",
      value: "+299",
      label: "GL",
    },
    {
      name: "Grenada",
      value: "+1473",
      label: "GD",
    },
    {
      name: "Guadeloupe",
      value: "+590",
      label: "GP",
    },
    {
      name: "Guam",
      value: "+1671",
      label: "GU",
    },
    {
      name: "Guatemala",
      value: "+502",
      label: "GT",
    },
    {
      name: "Guernsey",
      value: "+44",
      label: "GG",
    },
    {
      name: "Guinea",
      value: "+224",
      label: "GN",
    },
    {
      name: "Guinea-Bissau",
      value: "+245",
      label: "GW",
    },
    {
      name: "Guyana",
      value: "+595",
      label: "GY",
    },
    {
      name: "Haiti",
      value: "+509",
      label: "HT",
    },
    {
      name: "Holy See (Vatican City State)",
      value: "+379",
      label: "VA",
    },
    {
      name: "Honduras",
      value: "+504",
      label: "HN",
    },
    {
      name: "Hong Kong",
      value: "+852",
      label: "HK",
    },
    {
      name: "Hungary",
      value: "+36",
      label: "HU",
    },
    {
      name: "Iceland",
      value: "+354",
      label: "IS",
    },
    {
      name: "India",
      value: "+91",
      label: "IN",
    },
    {
      name: "Indonesia",
      value: "+62",
      label: "ID",
    },
    {
      name: "Iran, Islamic Republic of Persian Gulf",
      value: "+98",
      label: "IR",
    },
    {
      name: "Iraq",
      value: "+964",
      label: "IQ",
    },
    {
      name: "Ireland",
      value: "+353",
      label: "IE",
    },
    {
      name: "Isle of Man",
      value: "+44",
      label: "IM",
    },
    {
      name: "Israel",
      value: "+972",
      label: "IL",
    },
    {
      name: "Italy",
      value: "+39",
      label: "IT",
    },
    {
      name: "Jamaica",
      value: "+1876",
      label: "JM",
    },
    {
      name: "Japan",
      value: "+81",
      label: "JP",
    },
    {
      name: "Jersey",
      value: "+44",
      label: "JE",
    },
    {
      name: "Jordan",
      value: "+962",
      label: "JO",
    },
    {
      name: "Kazakhstan",
      value: "+77",
      label: "KZ",
    },
    {
      name: "Kenya",
      value: "+254",
      label: "KE",
    },
    {
      name: "Kiribati",
      value: "+686",
      label: "KI",
    },
    {
      name: "Korea, Democratic People's Republic of Korea",
      value: "+850",
      label: "KP",
    },
    {
      name: "Korea, Republic of South Korea",
      value: "+82",
      label: "KR",
    },
    {
      name: "Kuwait",
      value: "+965",
      label: "KW",
    },
    {
      name: "Kyrgyzstan",
      value: "+996",
      label: "KG",
    },
    {
      name: "Laos",
      value: "+856",
      label: "LA",
    },
    {
      name: "Latvia",
      value: "+371",
      label: "LV",
    },
    {
      name: "Lebanon",
      value: "+961",
      label: "LB",
    },
    {
      name: "Lesotho",
      value: "+266",
      label: "LS",
    },
    {
      name: "Liberia",
      value: "+231",
      label: "LR",
    },
    {
      name: "Libyan Arab Jamahiriya",
      value: "+218",
      label: "LY",
    },
    {
      name: "Liechtenstein",
      value: "+423",
      label: "LI",
    },
    {
      name: "Lithuania",
      value: "+370",
      label: "LT",
    },
    {
      name: "Luxembourg",
      value: "+352",
      label: "LU",
    },
    {
      name: "Macao",
      value: "+853",
      label: "MO",
    },
    {
      name: "Macedonia",
      value: "+389",
      label: "MK",
    },
    {
      name: "Madagascar",
      value: "+261",
      label: "MG",
    },
    {
      name: "Malawi",
      value: "+265",
      label: "MW",
    },
    {
      name: "Malaysia",
      value: "+60",
      label: "MY",
    },
    {
      name: "Maldives",
      value: "+960",
      label: "MV",
    },
    {
      name: "Mali",
      value: "+223",
      label: "ML",
    },
    {
      name: "Malta",
      value: "+356",
      label: "MT",
    },
    {
      name: "Marshall Islands",
      value: "+692",
      label: "MH",
    },
    {
      name: "Martinique",
      value: "+596",
      label: "MQ",
    },
    {
      name: "Mauritania",
      value: "+222",
      label: "MR",
    },
    {
      name: "Mauritius",
      value: "+230",
      label: "MU",
    },
    {
      name: "Mayotte",
      value: "+262",
      label: "YT",
    },
    {
      name: "Mexico",
      value: "+52",
      label: "MX",
    },
    {
      name: "Micronesia, Federated States of Micronesia",
      value: "+691",
      label: "FM",
    },
    {
      name: "Moldova",
      value: "+373",
      label: "MD",
    },
    {
      name: "Monaco",
      value: "+377",
      label: "MC",
    },
    {
      name: "Mongolia",
      value: "+976",
      label: "MN",
    },
    {
      name: "Montenegro",
      value: "+382",
      label: "ME",
    },
    {
      name: "Montserrat",
      value: "+1664",
      label: "MS",
    },
    {
      name: "Morocco",
      value: "+212",
      label: "MA",
    },
    {
      name: "Mozambique",
      value: "+258",
      label: "MZ",
    },
    {
      name: "Myanmar",
      value: "+95",
      label: "MM",
    },
    {
      name: "Namibia",
      value: "+264",
      label: "NA",
    },
    {
      name: "Nauru",
      value: "+674",
      label: "NR",
    },
    {
      name: "Nepal",
      value: "+977",
      label: "NP",
    },
    {
      name: "Netherlands",
      value: "+31",
      label: "NL",
    },
    {
      name: "Netherlands Antilles",
      value: "+599",
      label: "AN",
    },
    {
      name: "New Caledonia",
      value: "+687",
      label: "NC",
    },
    {
      name: "New Zealand",
      value: "+64",
      label: "NZ",
    },
    {
      name: "Nicaragua",
      value: "+505",
      label: "NI",
    },
    {
      name: "Niger",
      value: "+227",
      label: "NE",
    },
    {
      name: "Nigeria",
      value: "+234",
      label: "NG",
    },
    {
      name: "Niue",
      value: "+683",
      label: "NU",
    },
    {
      name: "Norfolk Island",
      value: "+672",
      label: "NF",
    },
    {
      name: "Northern Mariana Islands",
      value: "+1670",
      label: "MP",
    },
    {
      name: "Norway",
      value: "+47",
      label: "NO",
    },
    {
      name: "Oman",
      value: "+968",
      label: "OM",
    },
    {
      name: "Pakistan",
      value: "+92",
      label: "PK",
    },
    {
      name: "Palau",
      value: "+680",
      label: "PW",
    },
    {
      name: "Palestinian Territory, Occupied",
      value: "+970",
      label: "PS",
    },
    {
      name: "Panama",
      value: "+507",
      label: "PA",
    },
    {
      name: "Papua New Guinea",
      value: "+675",
      label: "PG",
    },
    {
      name: "Paraguay",
      value: "+595",
      label: "PY",
    },
    {
      name: "Peru",
      value: "+51",
      label: "PE",
    },
    {
      name: "Philippines",
      value: "+63",
      label: "PH",
    },
    {
      name: "Pitcairn",
      value: "+872",
      label: "PN",
    },
    {
      name: "Poland",
      value: "+48",
      label: "PL",
    },
    {
      name: "Portugal",
      value: "+351",
      label: "PT",
    },
    {
      name: "Puerto Rico",
      value: "+1939",
      label: "PR",
    },
    {
      name: "Qatar",
      value: "+974",
      label: "QA",
    },
    {
      name: "Romania",
      value: "+40",
      label: "RO",
    },
    {
      name: "Russia",
      value: "+7",
      label: "RU",
    },
    {
      name: "Rwanda",
      value: "+250",
      label: "RW",
    },
    {
      name: "Reunion",
      value: "+262",
      label: "RE",
    },
    {
      name: "Saint Barthelemy",
      value: "+590",
      label: "BL",
    },
    {
      name: "Saint Helena, Ascension and Tristan Da Cunha",
      value: "+290",
      label: "SH",
    },
    {
      name: "Saint Kitts and Nevis",
      value: "+1869",
      label: "KN",
    },
    {
      name: "Saint Lucia",
      value: "+1758",
      label: "LC",
    },
    {
      name: "Saint Martin",
      value: "+590",
      label: "MF",
    },
    {
      name: "Saint Pierre and Miquelon",
      value: "+508",
      label: "PM",
    },
    {
      name: "Saint Vincent and the Grenadines",
      value: "+1784",
      label: "VC",
    },
    {
      name: "Samoa",
      value: "+685",
      label: "WS",
    },
    {
      name: "San Marino",
      value: "+378",
      label: "SM",
    },
    {
      name: "Sao Tome and Principe",
      value: "+239",
      label: "ST",
    },
    {
      name: "Saudi Arabia",
      value: "+966",
      label: "SA",
    },
    {
      name: "Senegal",
      value: "+221",
      label: "SN",
    },
    {
      name: "Serbia",
      value: "+381",
      label: "RS",
    },
    {
      name: "Seychelles",
      value: "+248",
      label: "SC",
    },
    {
      name: "Sierra Leone",
      value: "+232",
      label: "SL",
    },
    {
      name: "Singapore",
      value: "+65",
      label: "SG",
    },
    {
      name: "Slovakia",
      value: "+421",
      label: "SK",
    },
    {
      name: "Slovenia",
      value: "+386",
      label: "SI",
    },
    {
      name: "Solomon Islands",
      value: "+677",
      label: "SB",
    },
    {
      name: "Somalia",
      value: "+252",
      label: "SO",
    },
    {
      name: "South Africa",
      value: "+27",
      label: "ZA",
    },
    {
      name: "South Sudan",
      value: "+211",
      label: "SS",
    },
    {
      name: "South Georgia and the South Sandwich Islands",
      value: "+500",
      label: "GS",
    },
    {
      name: "Spain",
      value: "+34",
      label: "ES",
    },
    {
      name: "Sri Lanka",
      value: "+94",
      label: "LK",
    },
    {
      name: "Sudan",
      value: "+249",
      label: "SD",
    },
    {
      name: "Suriname",
      value: "+597",
      label: "SR",
    },
    {
      name: "Svalbard and Jan Mayen",
      value: "+47",
      label: "SJ",
    },
    {
      name: "Swaziland",
      value: "+268",
      label: "SZ",
    },
    {
      name: "Sweden",
      value: "+46",
      label: "SE",
    },
    {
      name: "Switzerland",
      value: "+41",
      label: "CH",
    },
    {
      name: "Syrian Arab Republic",
      value: "+963",
      label: "SY",
    },
    {
      name: "Taiwan",
      value: "+886",
      label: "TW",
    },
    {
      name: "Tajikistan",
      value: "+992",
      label: "TJ",
    },
    {
      name: "Tanzania, United Republic of Tanzania",
      value: "+255",
      label: "TZ",
    },
    {
      name: "Thailand",
      value: "+66",
      label: "TH",
    },
    {
      name: "Timor-Leste",
      value: "+670",
      label: "TL",
    },
    {
      name: "Togo",
      value: "+228",
      label: "TG",
    },
    {
      name: "Tokelau",
      value: "+690",
      label: "TK",
    },
    {
      name: "Tonga",
      value: "+676",
      label: "TO",
    },
    {
      name: "Trinidad and Tobago",
      value: "+1868",
      label: "TT",
    },
    {
      name: "Tunisia",
      value: "+216",
      label: "TN",
    },
    {
      name: "Turkey",
      value: "+90",
      label: "TR",
    },
    {
      name: "Turkmenistan",
      value: "+993",
      label: "TM",
    },
    {
      name: "Turks and Caicos Islands",
      value: "+1649",
      label: "TC",
    },
    {
      name: "Tuvalu",
      value: "+688",
      label: "TV",
    },
    {
      name: "Uganda",
      value: "+256",
      label: "UG",
    },
    {
      name: "Ukraine",
      value: "+380",
      label: "UA",
    },
    {
      name: "United Arab Emirates",
      value: "+971",
      label: "AE",
    },
    {
      name: "United Kingdom",
      value: "+44",
      label: "GB",
    },
    {
      name: "United States",
      value: "+1",
      label: "US",
    },
    {
      name: "Uruguay",
      value: "+598",
      label: "UY",
    },
    {
      name: "Uzbekistan",
      value: "+998",
      label: "UZ",
    },
    {
      name: "Vanuatu",
      value: "+678",
      label: "VU",
    },
    {
      name: "Venezuela, Bolivarian Republic of Venezuela",
      value: "+58",
      label: "VE",
    },
    {
      name: "Vietnam",
      value: "+84",
      label: "VN",
    },
    {
      name: "Virgin Islands, British",
      value: "+1284",
      label: "VG",
    },
    {
      name: "Virgin Islands, U.S.",
      value: "+1340",
      label: "VI",
    },
    {
      name: "Wallis and Futuna",
      value: "+681",
      label: "WF",
    },
    {
      name: "Yemen",
      value: "+967",
      label: "YE",
    },
    {
      name: "Zambia",
      value: "+260",
      label: "ZM",
    },
    {
      name: "Zimbabwe",
      value: "+263",
      label: "ZW",
    },
  ];
}

function featherIconsList() {
  return [
    { icon: "core/activity", shape: Icons.Activity },
    { icon: "core/airplay", shape: Icons.Airplay },
    { icon: "core/alert-circle", shape: Icons.AlertCircle },
    { icon: "core/alert-octagon", shape: Icons.AlertOctagon },
    { icon: "core/alert-triangle", shape: Icons.AlertTriangle },
    { icon: "core/align-center", shape: Icons.AlignCenter },
    { icon: "core/align-justify", shape: Icons.AlignJustify },
    { icon: "core/align-left", shape: Icons.AlignLeft },
    { icon: "core/align-right", shape: Icons.AlignRight },
    { icon: "core/anchor", shape: Icons.Anchor },
    { icon: "core/at-sign", shape: Icons.AtSign },
    { icon: "core/award", shape: Icons.Award },
    { icon: "core/bar-chart-2", shape: Icons.BarChart2 },
    { icon: "core/bar-chart", shape: Icons.BarChart },
    { icon: "core/battery-charging", shape: Icons.BatteryCharging },
    { icon: "core/battery", shape: Icons.Battery },
    { icon: "core/bell-off", shape: Icons.BellOff },
    { icon: "core/bell", shape: Icons.Bell },
    { icon: "core/bluetooth", shape: Icons.Bluetooth },
    { icon: "core/book", shape: Icons.Book },
    { icon: "core/bookmark", shape: Icons.Bookmark },
    { icon: "core/box", shape: Icons.Box },
    { icon: "core/briefcase", shape: Icons.Briefcase },
    { icon: "core/calendar", shape: Icons.Calendar },
    { icon: "core/cast", shape: Icons.Cast },
    { icon: "core/check-circle", shape: Icons.CheckCircle },
    { icon: "core/check-square", shape: Icons.CheckSquare },
    { icon: "core/check", shape: Icons.Check },
    { icon: "core/circle", shape: Icons.Circle },
    { icon: "core/clipboard", shape: Icons.Clipboard },
    { icon: "core/clock", shape: Icons.Clock },
    { icon: "core/cloud-off", shape: Icons.CloudOff },
    { icon: "core/cloud", shape: Icons.Cloud },
    { icon: "core/command", shape: Icons.Command },
    { icon: "core/copy", shape: Icons.Copy },
    { icon: "core/cpu", shape: Icons.Cpu },
    { icon: "core/delete", shape: Icons.Delete },
    { icon: "core/disc", shape: Icons.Disc },
    { icon: "core/download-cloud", shape: Icons.DownloadCloud },
    { icon: "core/download", shape: Icons.Download },
    { icon: "core/edit-2", shape: Icons.Edit2 },
    { icon: "core/edit-3", shape: Icons.Edit3 },
    { icon: "core/edit", shape: Icons.Edit },
    { icon: "core/external-link", shape: Icons.ExternalLink },
    { icon: "core/eye-off", shape: Icons.EyeOff },
    { icon: "core/eye", shape: Icons.Eye },
    { icon: "core/feather", shape: Icons.Feather },
    { icon: "core/file", shape: Icons.File },
    { icon: "core/filter", shape: Icons.Filter },
    { icon: "core/flag", shape: Icons.Flag },
    { icon: "core/folder", shape: Icons.Folder },
    { icon: "core/grid", shape: Icons.Grid },
    { icon: "core/hash", shape: Icons.Hash },
    { icon: "core/headphones", shape: Icons.Headphones },
    { icon: "core/heart", shape: Icons.Heart },
    { icon: "core/home", shape: Icons.Home },
    { icon: "core/inbox", shape: Icons.Inbox },
    { icon: "core/info", shape: Icons.Info },
    { icon: "core/layers", shape: Icons.Layers },
    { icon: "core/layout", shape: Icons.Layout },
    { icon: "core/life-buoy", shape: Icons.LifeBuoy },
    { icon: "core/link-2", shape: Icons.Link2 },
    { icon: "core/link", shape: Icons.Link },
    { icon: "core/list", shape: Icons.List },
    { icon: "core/loader", shape: Icons.Loader },
    { icon: "core/lock", shape: Icons.Lock },
    { icon: "core/log-in", shape: Icons.LogIn },
    { icon: "core/log-out", shape: Icons.LogOut },
    { icon: "core/maximize-2", shape: Icons.Maximize2 },
    { icon: "core/maximize", shape: Icons.Maximize },
    { icon: "core/menu", shape: Icons.Menu },
    { icon: "core/mic-off", shape: Icons.MicOff },
    { icon: "core/mic", shape: Icons.Mic },
    { icon: "core/minimize-2", shape: Icons.Minimize2 },
    { icon: "core/minimize", shape: Icons.Minimize },
    { icon: "core/minus-circle", shape: Icons.MinusCircle },
    { icon: "core/minus-square", shape: Icons.MinusSquare },
    { icon: "core/minus", shape: Icons.Minus },
    { icon: "core/monitor", shape: Icons.Monitor },
    { icon: "core/more-horizontal", shape: Icons.MoreHorizontal },
    { icon: "core/more-vertical", shape: Icons.MoreVertical },
    { icon: "core/move", shape: Icons.Move },
    { icon: "core/music", shape: Icons.Music },
    { icon: "core/octagon", shape: Icons.Octagon },
    { icon: "core/package", shape: Icons.Package },
    { icon: "core/pie-chart", shape: Icons.PieChart },
    { icon: "core/plus-circle", shape: Icons.PlusCircle },
    { icon: "core/plus-square", shape: Icons.PlusSquare },
    { icon: "core/plus", shape: Icons.Plus },
    { icon: "core/power", shape: Icons.Power },
    { icon: "core/printer", shape: Icons.Printer },
    { icon: "core/radio", shape: Icons.Radio },
    { icon: "core/refresh-ccw", shape: Icons.RefreshCcw },
    { icon: "core/refresh-cw", shape: Icons.RefreshCw },
    { icon: "core/rotate-ccw", shape: Icons.RotateCcw },
    { icon: "core/rotate-cw", shape: Icons.RotateCw },
    { icon: "core/scissors", shape: Icons.Scissors },
    { icon: "core/search", shape: Icons.Search },
    { icon: "core/settings", shape: Icons.Settings },
    { icon: "core/share-2", shape: Icons.Share2 },
    { icon: "core/share", shape: Icons.Share },
    { icon: "core/slash", shape: Icons.Slash },
    { icon: "core/speaker", shape: Icons.Speaker },
    { icon: "core/square", shape: Icons.Square },
    { icon: "core/star", shape: Icons.Star },
    { icon: "core/tag", shape: Icons.Tag },
    { icon: "core/target", shape: Icons.Target },
    { icon: "core/thumbs-down", shape: Icons.ThumbsDown },
    { icon: "core/thumbs-up", shape: Icons.ThumbsUp },
    { icon: "core/toggle-left", shape: Icons.ToggleLeft },
    { icon: "core/toggle-right", shape: Icons.ToggleRight },
    { icon: "core/trash-2", shape: Icons.Trash2 },
    { icon: "core/trash", shape: Icons.Trash },
    { icon: "core/trending-down", shape: Icons.TrendingDown },
    { icon: "core/trending-up", shape: Icons.TrendingUp },
    { icon: "core/triangle", shape: Icons.Triangle },
    { icon: "core/type", shape: Icons.Type },
    { icon: "core/unlock", shape: Icons.Unlock },
    { icon: "core/upload-cloud", shape: Icons.UploadCloud },
    { icon: "core/upload", shape: Icons.Upload },
    { icon: "core/user-check", shape: Icons.UserCheck },
    { icon: "core/user-minus", shape: Icons.UserMinus },
    { icon: "core/user-plus", shape: Icons.UserPlus },
    { icon: "core/user-x", shape: Icons.UserX },
    { icon: "core/user", shape: Icons.User },
    { icon: "core/watch", shape: Icons.Watch },
    { icon: "core/wifi", shape: Icons.Wifi },
    { icon: "core/x-circle", shape: Icons.XCircle },
    { icon: "core/x-square", shape: Icons.XSquare },
    { icon: "core/x", shape: Icons.X },
    { icon: "core/zap", shape: Icons.Zap },
    { icon: "core/zoom-in", shape: Icons.ZoomIn },
    { icon: "core/zoom-out", shape: Icons.ZoomOut },
    { icon: "media-controls/fast-forward", shape: Icons.FastForward },
    { icon: "media-controls/pause", shape: Icons.Pause },
    { icon: "media-controls/play", shape: Icons.Play },
    { icon: "media-controls/repeat", shape: Icons.Repeat },
    { icon: "media-controls/rewind", shape: Icons.Rewind },
    { icon: "media-controls/shuffle", shape: Icons.Shuffle },
    { icon: "media-controls/skip-back", shape: Icons.SkipBack },
    { icon: "media-controls/skip-forward", shape: Icons.SkipForward },
    { icon: "media-controls/volume-1", shape: Icons.Volume1 },
    { icon: "media-controls/volume-2", shape: Icons.Volume2 },
    { icon: "media-controls/volume-x", shape: Icons.VolumeX },
    { icon: "media-controls/volume", shape: Icons.Volume },
    { icon: "communication/mail", shape: Icons.Mail },
    { icon: "communication/message-circle", shape: Icons.MessageCircle },
    { icon: "communication/message-square", shape: Icons.MessageSquare },
    { icon: "communication/phone-call", shape: Icons.PhoneCall },
    { icon: "communication/phone-forwarded", shape: Icons.PhoneForwarded },
    { icon: "communication/phone-incoming", shape: Icons.PhoneIncoming },
    { icon: "communication/phone-missed", shape: Icons.PhoneMissed },
    { icon: "communication/phone-off", shape: Icons.PhoneOff },
    { icon: "communication/phone-outgoing", shape: Icons.PhoneOutgoing },
    { icon: "communication/phone", shape: Icons.Phone },
    { icon: "communication/voicemail", shape: Icons.Voicemail },
    { icon: "photo-and-video/aperture", shape: Icons.Aperture },
    { icon: "photo-and-video/camera-off", shape: Icons.CameraOff },
    { icon: "photo-and-video/camera", shape: Icons.Camera },
    { icon: "photo-and-video/image", shape: Icons.Image },
    { icon: "photo-and-video/video-off", shape: Icons.VideoOff },
    { icon: "photo-and-video/video", shape: Icons.Video },
    { icon: "location/compass", shape: Icons.Compass },
    { icon: "location/crosshair", shape: Icons.Crosshair },
    { icon: "location/globe", shape: Icons.Globe },
    { icon: "location/map-pin", shape: Icons.MapPin },
    { icon: "location/map", shape: Icons.Map },
    { icon: "location/navigation-2", shape: Icons.Navigation2 },
    { icon: "location/navigation", shape: Icons.Navigation },
    { icon: "weather/cloud-drizzle", shape: Icons.CloudDrizzle },
    { icon: "weather/cloud-lightning", shape: Icons.CloudLightning },
    { icon: "weather/cloud-rain", shape: Icons.CloudRain },
    { icon: "weather/cloud-snow", shape: Icons.CloudSnow },
    { icon: "weather/droplet", shape: Icons.Droplet },
    { icon: "weather/moon", shape: Icons.Moon },
    { icon: "weather/sun", shape: Icons.Sun },
    { icon: "weather/sunrise", shape: Icons.Sunrise },
    { icon: "weather/sunset", shape: Icons.Sunset },
    { icon: "weather/thermometer", shape: Icons.Thermometer },
    { icon: "weather/umbrella", shape: Icons.Umbrella },
    { icon: "weather/wind", shape: Icons.Wind },
    { icon: "arrows/arrow-down-left", shape: Icons.ArrowDownLeft },
    { icon: "arrows/arrow-down-right", shape: Icons.ArrowDownRight },
    { icon: "arrows/arrow-down", shape: Icons.ArrowDown },
    { icon: "arrows/arrow-left", shape: Icons.ArrowLeft },
    { icon: "arrows/arrow-right", shape: Icons.ArrowRight },
    { icon: "arrows/arrow-up-left", shape: Icons.ArrowUpLeft },
    { icon: "arrows/arrow-up-right", shape: Icons.ArrowUpRight },
    { icon: "arrows/arrow-up", shape: Icons.ArrowUp },
    { icon: "arrows/chevron-down", shape: Icons.ChevronDown },
    { icon: "arrows/chevron-left", shape: Icons.ChevronLeft },
    { icon: "arrows/chevron-right", shape: Icons.ChevronRight },
    { icon: "arrows/chevron-up", shape: Icons.ChevronUp },
    { icon: "arrows/chevrons-down", shape: Icons.ChevronsDown },
    { icon: "arrows/chevrons-left", shape: Icons.ChevronsLeft },
    { icon: "arrows/chevrons-right", shape: Icons.ChevronsRight },
    { icon: "arrows/chevrons-up", shape: Icons.ChevronsUp },
    { icon: "logos/chrome", shape: Icons.Chrome },
    { icon: "logos/codepen", shape: Icons.Codepen },
    { icon: "logos/facebook", shape: Icons.Facebook },
    { icon: "logos/instagram", shape: Icons.Instagram },
    { icon: "logos/pocket", shape: Icons.Pocket },
    { icon: "logos/slack", shape: Icons.Slack },
    { icon: "logos/twitter", shape: Icons.Twitter },
  ];
}

module.exports = {
  countriesList,
  featherIconsList,
  componentCategoryList,
  sectionsList,
};
