import Head from 'next/head';
import React from 'react';


function classNames(...classes) {
  return classes.filter(Boolean).join(' ')
}

export default function Example() {


  return (

     <div className='relative mx-auto max-w-3xl pt-20 text-left pb-24 '>
      <Head>
        <title>Sites60 - Terms and Conditions</title>
      </Head>
      <div className="relative mx-auto pt-20 text-center pb-24">
        <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">Terms and Conditions</h1>
        <p class="mt-4 text-base leading-7 text-slate-600">Last updated on June 14, 2023</p>
        </div>
        <div className='mx-auto  w-full'>
        <p className="text-gray-600 text-lg">Please read these Terms and Conditions ("Terms") carefully before using Sites60, a drag and drop website builder with AI content generator (referred to as "the Product") operated by Sites60 (referred to as "we," "us," or "our").</p>

        <p className="text-gray-600 text-lg mt-8">By using the Product, you agree to be bound by these Terms. If you do not agree with any part of these Terms, you may not use the Product.</p>

        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">1. License to Use</h2>
          <p className="text-gray-600 text-lg">
            1.1. We grant you a limited, non-exclusive, non-transferable license to use the Product for the purpose of creating and managing websites.
          </p>
          <p className="text-gray-600 text-lg">
            1.2. You may not modify, reproduce, distribute, or create derivative works based on the Product without our prior written consent.
          </p>
          <p className="text-gray-600 text-lg">
            1.3. We reserve the right to suspend or terminate your access to the Product at any time without prior notice if you violate these Terms.
          </p>
        </div>

        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">2. User Content</h2>
          <p className="text-gray-600 text-lg">
            2.1. You are solely responsible for the content you generate using the Product, including text, images, videos, and any other materials ("User Content").
          </p>
          <p className="text-gray-600 text-lg">
            2.2. You represent and warrant that you own or have the necessary rights and permissions to use and publish the User Content.
          </p>
          <p className="text-gray-600 text-lg">
            2.3. We do not claim ownership over the User Content, but by using the Product, you grant us a worldwide, royalty-free, non-exclusive license to use, display, and distribute the User Content for the purpose of providing and improving the Product.
          </p>
          <p className="text-gray-600 text-lg">
            2.4. You are solely responsible for the legality, accuracy, and appropriateness of the User Content.
          </p>
        </div>

        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">3. Intellectual Property</h2>
          <p className="text-gray-600 text-lg">
            3.1. The Product, including its design, features, and functionality, is owned by us and is protected by intellectual property laws.
          </p>
          <p className="text-gray-600 text-lg">
            3.2. You may not copy, modify, distribute, or reverse engineer the Product or any part thereof.
          </p>
          <p className="text-gray-600 text-lg">
            3.3. The trademarks, logos, and service marks displayed in connection with the Product are our registered and unregistered trademarks. You may not use these trademarks without our prior written consent.
          </p>
        </div>

        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">4. Privacy</h2>
          <p className="text-gray-600 text-lg">
            4.1. We collect and process personal information in accordance with our Privacy Policy. By using the Product, you consent to the collection and processing of your personal information as described in the Privacy Policy.
          </p>
        </div>

        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">5. Limitation of Liability</h2>
          <p className="text-gray-600 text-lg">
            5.1. The Product is provided on an "as-is" and "as available" basis, without any warranties or conditions, expressed or implied.
          </p>
          <p className="text-gray-600 text-lg">
            5.2. We shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or in connection with the use or inability to use the Product.
          </p>
          <p className="text-gray-600 text-lg">
            5.3. We do not guarantee the accuracy, reliability, or completeness of any content generated by the AI content generator.
          </p>
        </div>

        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">6. Termination</h2>
          <p className="text-gray-600 text-lg">
            6.1. We may suspend or terminate your access to the Product at any time without prior notice if you violate these Terms.
          </p>
          <p className="text-gray-600 text-lg">
            6.2. Upon termination, all licenses and rights granted to you in relation to the Product will immediately cease.
          </p>
        </div>

        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">7. Modifications</h2>
          <p className="text-gray-600 text-lg">
            7.1. We reserve the right to modify these Terms at any time. Any changes to the Terms will be effective immediately upon posting the revised version on our website.
          </p>
          <p className="text-gray-600 text-lg">
            7.2. Your continued use of the Product after the posting of any changes constitutes your acceptance of such changes.
          </p>
        </div>

        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">8. Governing Law</h2>
          <p className="text-gray-600 text-lg">
            8.1. These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions, and each party agrees to submit itself to the exclusive jurisdiction of the courts of Hyderabad, Telangana, India.
          </p>
        </div>

        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">9. Severability</h2>
          <p className="text-gray-600 text-lg">
            9.1. If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall continue to be valid and enforceable to the fullest extent permitted by law.
          </p>
        </div>

        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">10. Entire Agreement</h2>
          <p className="text-gray-600 text-lg">
            10.1. These Terms constitute the entire agreement between you and us regarding the use of the Product and supersede any prior agreements or understandings, whether written or oral.
          </p>
        </div>

        <div className="mt-8">
          <p className="text-gray-600 text-lg">
            By using the Product, you acknowledge that you have read, understood, and agree to be bound by these Terms and any other guidelines or policies referenced herein. If you do not agree to these Terms, you should not use the Product.
          </p>
        </div>

        <div className="mt-8">
          <p className="text-gray-600 text-lg">
            If you have any questions or concerns about these Terms, please contact us at rajeev@techub.in.
          </p>
        </div>

        {/* <div className="mt-8">
          <p className="text-gray-600 text-lg">
            Date of Last Revision: [Insert Date]
          </p>
        </div> */}
      </div>
    </div>
  )
}
